-- Categorias editables para servicios.
-- Ejecutar una sola vez en Supabase. Sirve para todos los negocios.

ALTER TABLE public.servicios
ADD COLUMN IF NOT EXISTS categoria text DEFAULT 'otros';

CREATE TABLE IF NOT EXISTS public.categorias_servicios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id uuid NOT NULL REFERENCES public.negocios(id) ON DELETE CASCADE,
  nombre text NOT NULL,
  slug text NOT NULL,
  icono text DEFAULT '⭐',
  orden integer DEFAULT 99,
  activo boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (negocio_id, slug)
);

CREATE INDEX IF NOT EXISTS idx_categorias_servicios_negocio
ON public.categorias_servicios (negocio_id, activo, orden);

CREATE INDEX IF NOT EXISTS idx_servicios_negocio_categoria
ON public.servicios (negocio_id, categoria);

ALTER TABLE public.categorias_servicios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "categorias_servicios_read" ON public.categorias_servicios;
CREATE POLICY "categorias_servicios_read"
ON public.categorias_servicios FOR SELECT
USING (true);

DROP POLICY IF EXISTS "categorias_servicios_insert" ON public.categorias_servicios;
CREATE POLICY "categorias_servicios_insert"
ON public.categorias_servicios FOR INSERT
WITH CHECK (true);

DROP POLICY IF EXISTS "categorias_servicios_update" ON public.categorias_servicios;
CREATE POLICY "categorias_servicios_update"
ON public.categorias_servicios FOR UPDATE
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "categorias_servicios_delete" ON public.categorias_servicios;
CREATE POLICY "categorias_servicios_delete"
ON public.categorias_servicios FOR DELETE
USING (true);

INSERT INTO public.categorias_servicios (negocio_id, nombre, slug, icono, orden, activo)
SELECT n.id, c.nombre, c.slug, c.icono, c.orden, true
FROM public.negocios n
CROSS JOIN (
  VALUES
    ('Manicura', 'manicura', '💅', 1),
    ('Pedicura', 'pedicura', '🦶', 2),
    ('Faciales', 'faciales', '✨', 3),
    ('Barbería', 'barberia', '💈', 4),
    ('Cejas', 'cejas', '👁️', 5),
    ('Combos', 'combos', '🎁', 6),
    ('Otros', 'otros', '⭐', 99)
) AS c(nombre, slug, icono, orden)
ON CONFLICT (negocio_id, slug) DO NOTHING;

UPDATE public.servicios
SET categoria = CASE
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%pedic%' THEN 'pedicura'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%pie%' THEN 'pedicura'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%facial%' THEN 'faciales'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%limpieza%' THEN 'faciales'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%barba%' THEN 'barberia'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%corte%' THEN 'barberia'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%ceja%' THEN 'cejas'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%pesta%' THEN 'cejas'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%combo%' THEN 'combos'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%paquete%' THEN 'combos'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%manic%' THEN 'manicura'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%uña%' THEN 'manicura'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%una%' THEN 'manicura'
  WHEN lower(coalesce(nombre, '') || ' ' || coalesce(descripcion, '')) LIKE '%gel%' THEN 'manicura'
  ELSE coalesce(nullif(categoria, ''), 'otros')
END
WHERE categoria IS NULL OR categoria = '' OR categoria = 'otros';
